"""Added Token Count IN PROMO CODE DB

Revision ID: 53f22318824e
Revises: eec5705c4b15
Create Date: 2023-07-02 14:37:43.328463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f22318824e'
down_revision = 'eec5705c4b15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_code', sa.Column('token', sa.INTEGER(), nullable=False))
    op.drop_column('used_promo_codes', 'used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('used_promo_codes', sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('promo_code', 'token')
    # ### end Alembic commands ###
