"""Update for server

Revision ID: 60ae82603c12
Revises: 53f22318824e
Create Date: 2023-07-04 07:32:13.285994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ae82603c12'
down_revision = '53f22318824e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_promo_codes_promo_code'), 'promo_codes', ['promo_code'])
    op.add_column('used_promo_codes', sa.Column('promo_code', sa.VARCHAR(length=64), nullable=False))
    op.drop_column('used_promo_codes', 'promo_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('used_promo_codes', sa.Column('promo_codes', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('used_promo_codes', 'promo_code')
    op.drop_constraint(op.f('uq_promo_codes_promo_code'), 'promo_codes', type_='unique')
    # ### end Alembic commands ###
