"""Added subscribers tables

Revision ID: a49539d4e253
Revises: 60ae82603c12
Create Date: 2023-07-12 16:28:32.784951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49539d4e253'
down_revision = '60ae82603c12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_end_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_subscribers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_subscribers_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
