"""Added ref

Revision ID: d93676c4db32
Revises: ea933c40f5f2
Create Date: 2023-06-14 18:21:47.374965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93676c4db32'
down_revision = 'ea933c40f5f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_promo_codes_promo_code'), 'promo_codes', ['promo_codes'])
    op.create_unique_constraint(op.f('uq_used_promo_codes_id'), 'used_promo_codes', ['id'])
    op.add_column('users', sa.Column('referral_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(op.f('uq_users_user_id'), 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_user_id'), 'users', type_='unique')
    op.drop_column('users', 'referral_id')
    op.drop_constraint(op.f('uq_used_promo_codes_id'), 'used_promo_codes', type_='unique')
    op.drop_constraint(op.f('uq_promo_codes_promo_code'), 'promo_codes', type_='unique')
    # ### end Alembic commands ###
