"""New revision

Revision ID: ea933c40f5f2
Revises: 
Create Date: 2023-06-12 19:54:37.948327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea933c40f5f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('promo_codes', sa.VARCHAR(length=64), nullable=False),
    sa.Column('end_time', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('promo_codes', name=op.f('pk_promo_codes')),
    sa.UniqueConstraint('promo_codes', name=op.f('uq_promo_codes_promo_code'))
    )
    op.create_table('used_promo_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('promo_codes', sa.VARCHAR(length=64), nullable=False),
    sa.Column('used', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_used_promo_codes')),
    sa.UniqueConstraint('id', name=op.f('uq_used_promo_codes_id'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('second_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('role', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.INTEGER(), nullable=False),
    sa.Column('reg_data', sa.DATE(), nullable=False),
    sa.Column('update_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('user_id', name=op.f('uq_users_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('used_promo_codes')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
