"""Remove update date

Revision ID: eec5705c4b15
Revises: d93676c4db32
Create Date: 2023-06-23 21:27:14.100793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec5705c4b15'
down_revision = 'd93676c4db32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'update_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
